apiVersion: v1
kind: Service
metadata:
  name: doctor-management-service
spec:
  selector:
    app: doctor-management-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: NodePort
