apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-management-service
  template:
    metadata:
      labels:
        app: doctor-management-service
    spec:
      containers:
      - name: doctor-management-service
        image: doctor-management-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003