apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  labels:
    app: agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: 306489597667.dkr.ecr.ap-southeast-1.amazonaws.com/agentservice:latest
        ports:
        - containerPort: 8000