apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  labels:
    app: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insurance
        image: 306489597667.dkr.ecr.ap-southeast-1.amazonaws.com/insuranceservice:latest
        ports:
        - containerPort: 8001