name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build, Push, and Deploy Patient Record Service
      - name: Build Patient Record Service
        run: |
          docker build -t avishkaiit/patient-record-service:latest ./patient_record_service
      - name: Push Patient Record Service
        run: |
          docker push avishkaiit/patient-record-service:latest
      - name: Deploy Patient Record Service
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f ./patient_record_service/patient-record-service-deployment.yml
          kubectl apply -f ./patient_record_service/patient-record-service.yml

      # Build, Push, and Deploy Appointment Scheduling Service
      - name: Build Appointment Scheduling Service
        run: |
          docker build -t avishkaiit/appointment-scheduling-service .
      - name: Push Appointment Scheduling Service
        run: |
          docker push avishkaiit/appointment-scheduling-service:latest
      - name: Deploy Appointment Scheduling Service
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f appointment_scheduling_service/appointment-scheduling-service-deployment.yml
          kubectl apply -f appointment_scheduling_service/appointment-scheduling-service.yml

      # Build, Push, and Deploy Billing Service
      - name: Build Billing Service
        run: |
          docker build -t avishkaiit/billing-service/ .
      - name: Push Billing Service
        run: |
          docker push avishkaiit/billing-service:latest
      - name: Deploy Billing Service
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f billing_service/billing-service-deployment.yml
          kubectl apply -f billing_service/billing-service.yml

      # Build, Push, and Deploy Doctor Management Service
      - name: Build Doctor Management Service
        run: |
          docker build -t avishkaiit/doctor-management-service/ .
      - name: Push Doctor Management Service
        run: |
          docker push avishkaiit/doctor-management-service:latest
      - name: Deploy Doctor Management Service
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f doctor_management_service/doctor-management-service-deployment.yaml
          kubectl apply -f doctor_management_service/doctor-management-service.yaml
